version: '3.8'

services:
  gpt-proxy:
    image: nalvix/gpt-proxy:latest
    container_name: gpt-proxy
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "127.0.0.1:33013:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped 